<a href="https://colab.research.google.com/github/v-yunusic/REPO-PYTHON-VY/blob/main/two-centuries-um/Notebook/ultramarathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PIP

In [1]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests) (2026.7.22)
ERROR: Operation cancelled by user

In [1]:
pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.13/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from gdown) (4.0.7)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.13/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2026.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (1.7.1)

# LIBRERIAS

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import sympy as sp
import pandas as pd
import seaborn as sns
import re # RegEx
import random #Libreria random
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import gdown
import gc

#==========API REQUESTS==========#
from google.colab import userdata
import requests
import json
#========== PATH ==========#
from pathlib import Path
#========= KAGGLE =========#
import kagglehub

print('Librerias importadas!\n'+'-'*60)

Librerias importadas!
------------------------------------------------------------

# DIRECTORIOS

In [3]:
BASE_PATH = Path('.')
DATA_DIR = BASE_PATH / 'content'

# PREPROCESAMIENTO

In [3]:
countries = None

30

In [4]:
# https://drive.google.com/file/d/1z1JdNc9hZXbNxHaATZMrD_QcMR5qqMQG/view?usp=sharing

try:
  if not countries:
    file_id = '1z1JdNc9hZXbNxHaATZMrD_QcMR5qqMQG'
    url = f'https://drive.google.com/uc?id={file_id}'

    gdown.download(url, "UM_COUNTRIES.csv", quiet=True, use_cookies=False)

    countries = pd.read_csv('UM_COUNTRIES.csv', sep=',')
    print('\nDATAFRAME CARGADO!')
except:
  print(f'NO SE HA CARGADO DATAFRAME')

DATAFRAME CARGADO!

In [5]:
countries['Country'].unique()

array(['CHI', 'ARG', 'COL', 'RUS', 'SLO', 'HUN', 'GER', 'USA', 'CAN',
       'MEX', 'ITA', 'JPN', 'BLR', 'NED', 'BEL', 'FRA', 'GBR', 'CZE',
       'SRB', 'TPE', 'NZL', 'AUS', 'SGP', 'HKG', 'CHN', 'POL', 'LUX',
       'SUI', 'ROU', 'CRC', 'NGR', 'ESP', 'PAR', 'BRA', 'ISR', 'AUT',
       'SWE', 'UKR', 'SVK', 'MDA', 'UAE', 'DEN', 'THA', 'MAS', 'BUL',
       'GRE', 'ALB', 'SMR', 'PER', 'POR', 'CMR', 'IRL', 'LAT', 'ECU',
       'GUA', 'BRU', 'IND', 'INA', 'ALG', 'LIE', 'CRO', 'GUY', 'IRI',
       'PHI', 'URU', 'NOR', 'MAR', 'NCA', 'VIE', 'VEN', 'RSA', 'GAB',
       'TUR', 'LTU', 'FIN', 'TUN', 'QAT', 'CYP', 'ZIM', 'MOZ', 'LES',
       'MAW', 'BOT', 'NAM', 'SWZ', 'ZAM', 'MRI', 'KOR', 'CAM', 'SRI',
       'HON', 'BOL', 'PUR', 'GRL', 'UZB', 'BIH', 'MNE', 'MKD', 'MAC',
       'MDV', 'MGL', 'EST', 'JOR', 'UGA', 'NEP', 'EGY', 'KEN', 'JAM',
       'ESA', 'MLT', 'CAY', 'AND', 'DOM', 'HAI', 'ANG', 'KOS', 'ISL',
       'ETH', 'OMA', 'KAZ', 'AZE', 'FIJ', 'CHA', 'LBA', 'CPV', 'MAD',
       'MYA', 'AFG', 'LBN', 'PAN', 'CUB', 'TRI', 'ARM', 'BUR', 'PAK',
       'MON', 'IRE', 'CAF', 'SEN', 'TKM', 'IVB', 'SUD', 'ISV', 'CIV',
       'FRO', 'CGO', 'SOM', 'GAM', 'COD', 'TAN', 'BAN', 'KGZ', 'GIB',
       'KSA', 'BRN', 'RWA', 'BEN', 'IRQ', 'BHU', 'TWN', 'GEO', 'KUW',
       'SYR', 'NIG', 'BAH', 'TGA', 'MLI', 'ERI', 'TOG', 'COM', 'YEM',
       'COK', 'PNG', 'GUM', 'SAM', 'TJK', 'LAO', 'ARU', 'BIZ', 'MDG',
       'PLE', 'BER', 'BDI', 'PYF', 'GHA', 'BAR', 'LBR', 'STP', 'SKN',
       'SVE', 'DAN', 'NFI', 'MTN', 'GUI', 'ANT', 'GRN', 'SEY', 'GRB',
       'LCA', 'GBS', 'TKS', 'AHO', 'SLE', 'YUG', 'ACT'], dtype=object)

In [13]:
# PETICION DE DATA HACIA KAGGLE

try:
  path = kagglehub.dataset_download("aiaiaidavid/the-big-dataset-of-ultra-marathon-running")
  df = pd.read_csv('../kaggle/input/the-big-dataset-of-ultra-marathon-running/TWO_CENTURIES_OF_UM_RACES.csv')
  print('DATASET DE KAGGLE CARGADO!')
  print(path)
except Exception as e:
  print(f'Excepcion:\n{e}')

Using Colab cache for faster access to the 'the-big-dataset-of-ultra-marathon-running' dataset.
DATASET DE KAGGLE CARGADO!
/kaggle/input/the-big-dataset-of-ultra-marathon-running

In [15]:
df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [16]:
# https://drive.google.com/file/d/1KRlHOjpqcSrhCG5jHvhCjwsEzR4yiySZ/view?usp=sharing

try:
  if not df:
    file_id = '1KRlHOjpqcSrhCG5jHvhCjwsEzR4yiySZ'
    url = f'https://drive.google.com/uc?id={file_id}'

    gdown.download(url, "TWO_CENTURIES_OF_UM_RACES.csv", quiet=True, use_cookies=False)
    print('DATA CARGADA!')
except:
  print(f'NO SE HA CARGADO DATA.')

NO SE HA CARGADO DATA

##### ITERABLE

In [ ]:
#chunks = pd.read_csv('TWO_CENTURIES_OF_UM_RACES.csv', sep=',', chunksize=10000)

##### SEPARAR POR PAÍS DE ATLETA

In [ ]:
pais = 'CHI'.upper()

In [ ]:
df = None

In [ ]:
try:
  if not df:
    for c in pd.read_csv('TWO_CENTURIES_OF_UM_RACES.csv', sep=',', chunksize=10000):
      filtrado = c[c['Athlete country'] == pais]
      if not c.empty:
        df = pd.concat([df, filtrado])
    print('\nDATAFRAME GENERADO!')
except:
  print('\nNO SE HA GENERADO DATAFRAME')

NO SE HA GENERADO DATAFRAME

In [ ]:
df.head()

##### SEPARAR POR PAIS DE EVENTO

In [ ]:
df = None

In [ ]:
try:
  if not df:
    for c in pd.read_csv('TWO_CENTURIES_OF_UM_RACES.csv', sep=',', chunksize=10000):
      filtrado = c.loc[c['Event name'].str.find(pais) > -1]
      if not c.empty:
        df = pd.concat([df, filtrado])

    print('\nDATAFRAME GENERADO!')
except:
  print('\nNO SE HA GENERADO DATAFRAME')

NO SE HA GENERADO DATAFRAME

In [ ]:
df.head(2)

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1

In [ ]:
df.columns.tolist()

['Year of event',
 'Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers',
 'Athlete performance',
 'Athlete club',
 'Athlete country',
 'Athlete year of birth',
 'Athlete gender',
 'Athlete age category',
 'Athlete average speed',
 'Athlete ID']

In [ ]:
df = df[['Athlete ID',
 'Year of event',
 'Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers',
 'Athlete performance',
 'Athlete club',
 'Athlete country',
 'Athlete year of birth',
 'Athlete gender',
 'Athlete age category',
 'Athlete average speed']]

In [ ]:
df['Event name'].unique()

array(['Selva Costera (CHI)', 'Futangue Challenge 62k - Cerro Mayo (CHI)',
       'Futangue Challenge 62k - Elite (CHI)', 'Pucón Trail Run (CHI)',
       'Corralco Challenge (CHI)',
       'Ultra Fiord Patagonia Chile 70 Kms (CHI)',
       'Ultra Fiord Patagonia Chile 100 Kms (CHI)',
       'Ultra Fiord Patagonia Chile 100 Millas (CHI)',
       'Ultra Fiord Patagonia Chile 50 Kms (CHI)',
       'Huilo Huilo Trail Run (CHI)', 'Putaendo Trail (CHI)',
       'Torrencial Valdivia Trail 80K (CHI)', 'Frontera Trail (CHI)',
       'La Gran Travesía (CHI)', 'Endurance Challenge Chile 50 Kms (CHI)',
       'Endurance Challenge Chile 80 Kms (CHI)',
       'Endurance Challenge Chile 160 Kms (CHI)',
       'Atacama Crossing (CHI)',
       'Ultra Trail Torres del Paine 50 Kms (CHI)',
       'Ultra Trail Torres del Paine 80 Kms (CHI)',
       'Navarino Trail (CHI)', 'El Cañi Trail 50KM Ultra (CHI)',
       'El Cañi Trail 80KM Ultra Sky (CHI)',
       'Gran Travesía de los Valles Ultra-Trail (CHI)',
       'Cochrane Patagonia Trail (CHI)', 'Antarctic 100k Race (CHI)',
       '70kms Ultramaraton Lican Ray - Villarrica (CHI)',
       'Ultra Trail Andes Infernal (CHI)',
       'Ultra Fiord Patagonia Chile 100km (CHI)',
       'Ultra Fiord Patagonia Chile 70km (CHI)',
       'Ultra Fiord Patagonia Chile 50km (CHI)',
       'Ultra Fiord Patagonia Chile 100mi (CHI)',
       'Trail Adventure Torres del Paine 50km (CHI)',
       'Trail Adventure Torres del Paine 90km (CHI)',
       'Torrencial Valdivia Trail 60K (CHI)',
       'Trail Running Putaendo 60 Kms (CHI)',
       'Trail Running Putaendo 100 Kms (CHI)',
       'Endurance Challenge Chile 160km (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-73K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultraterra-100K (CHI)',
       '24 horas en pista Manquehue (CHI)',
       'Endurance Challenge Chile 50km (CHI)',
       'Endurance Challenge Chile 80km (CHI)',
       'Futangue Challenge 60k - Cerro Mayo (CHI)',
       'Ultra Fiord Patagonia Chile 50km - duo (CHI)',
       'Atacama Extreme 100 Miles (CHI)',
       'Torrencial Valdivia Trail 63K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-48K (CHI)',
       'Desafio a la Cruz Del Cabo Froward (CHI)',
       'Ultra Trail KoKamWaLa 60k (CHI)',
       'Pan American Race Walking Cup (CHI)', 'Tulahuen Ultra Run (CHI)',
       '24 horas en pista, Curico (CHI)',
       'Ultra Fiord Patagonia Chile 55 Kms (CHI)',
       'Atacama Crossing (Chile) (CHI)',
       'Ultramarathon Santiago-Vina del Mar (CHI)',
       '70 km Lican Ray-Villarrica (CHI)',
       'South American Race Walking Championships (CHI)',
       'Antarctic Ice Marathon Race (CHI)',
       'Copa Nacional de Marcha - Puerto Saavedra (CHI)',
       'Copa Nacional de Marcha - Los Angeles (CHI)',
       'Ultra Maraton de los Andes 80 Kms (CHI)',
       'Ultra Maraton de los Andes 50 Kms (CHI)',
       'Chilean Race Walking - Arica (CHI)',
       '100 Mile Polar Centenary Run (CHI)',
       'Rapa Nui GrandTrail 80 km (CHI)',
       'Vulcano Ultra Trail (VUT) (CHI)',
       'Patagonian Int. Marathon (CHI)',
       'Ultra Trail Torres del Paine 109km (CHI)',
       'Ultra Trail Torres del Paine 67km (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultraterra-80K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-64K (CHI)',
       'Atacama Extreme 50 Miles (CHI)', 'Atacama Extreme 50 Km (CHI)',
       'NACAC Race Walking Championships (CHI)',
       'Pan American Race Walking Cup - Man (CHI)',
       'Pan American Race Walking Cup - Woman (CHI)',
       'Ultra Trail Torres del Paine 50km (CHI)',
       'Puerto Varas 100km (CHI)'], dtype=object)

In [ ]:
print(f'Cantidad de filas:\n{df.shape[0]}')
print(f'Cantidad de columnas:\n{df.shape[1]}')

Cantidad de filas:
9792
Cantidad de columnas:
13

In [ ]:
print(f'Columnas presentes en el Dataframe:')
df.columns.tolist()

Columnas presentes en el Dataframe:

['Athlete ID',
 'Year of event',
 'Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers',
 'Athlete performance',
 'Athlete club',
 'Athlete country',
 'Athlete year of birth',
 'Athlete gender',
 'Athlete age category',
 'Athlete average speed']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9792 entries, 0 to 7076164
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Athlete ID                 9792 non-null   int64
 1   Year of event              9792 non-null   int64
 2   Event dates                9792 non-null   object
 3   Event name                 9792 non-null   object
 4   Event distance/length      9792 non-null   object
 5   Event number of finishers  9792 non-null   int64
 6   Athlete performance        9792 non-null   object
 7   Athlete club               1487 non-null   object
 8   Athlete country            9792 non-null   object
 9   Athlete year of birth      8946 non-null   float64
 10  Athlete gender             9792 non-null   object
 11  Athlete age category       8948 non-null   object
 12  Athlete average speed      9792 non-null   object
dtypes: float64(1), int64(3), object(9)
memory usage: 1.0+ MB

In [ ]:
# DEFINICION DE COLUMNAS NUMERICAS Y CATEGORICAS
col_categoricas = df.select_dtypes(include=['object']).columns.tolist()
col_numericas = df.select_dtypes(exclude=['object','bool']).columns.tolist()
col_bools = df.select_dtypes(include=['bool']).columns.tolist()

print(f'COLUMNAS NUMERICAS ({len(col_numericas)}):\n{col_numericas}\nCOLUMNAS CATEGORICAS ({len(col_categoricas)}):\n{col_categoricas}\nCOLUMNAS BOOLS ({len(col_bools)}):\n{col_bools}')

COLUMNAS NUMERICAS (4):
['Athlete ID', 'Year of event', 'Event number of finishers', 'Athlete year of birth']
COLUMNAS CATEGORICAS (9):
['Event dates', 'Event name', 'Event distance/length', 'Athlete performance', 'Athlete club', 'Athlete country', 'Athlete gender', 'Athlete age category', 'Athlete average speed']
COLUMNAS BOOLS (0):
[]

In [ ]:
df[col_categoricas].describe()

,Event dates,Event name,Event distance/length,Athlete performance,Athlete club,Athlete country,Athlete gender,Athlete age category,Athlete average speed
count,16115,16115,16115,16115,2558,16115,16115,15164,16115.000
unique,146,79,38,8574,559,81,2,19,5800.000
top,15.-16.04.2016,Atacama Crossing (CHI),50km,12:14:45 h,*Santiago,CHI,M,M23,4.034
freq,1050,1825,4721,21,316,9073,13127,4640,21.000